# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.info_api_api_slash import InfoApiApiSlash


class TestInfoApiApiSlash(unittest.TestCase):
    """ TestInfoApiApiSlash unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.info_api_api.InfoApiApiSlash()

    def tearDown(self):
        pass

    def test_info_using_get(self):
        """
        Test case for info_using_get

        info
        """
        pass


if __name__ == '__main__':
    unittest.main()
