# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.any_crs_geo_json_feature_geometry import AnyCrsGeoJsonFeatureGeometry


class TestAnyCrsGeoJsonFeatureGeometry(unittest.TestCase):
    """ AnyCrsGeoJsonFeatureGeometry unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyCrsGeoJsonFeatureGeometry(self):
        """
        Test AnyCrsGeoJsonFeatureGeometry
        """
        model = swagger_client.models.any_crs_geo_json_feature_geometry.AnyCrsGeoJsonFeatureGeometry()


if __name__ == '__main__':
    unittest.main()
