apiVersion: apps/v1
kind: Deployment
metadata:
  name: crs-converter-gke
  labels:
    app: crs-converter-gke
    version: v2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crs-converter-gke
      version: v2
  template:
    metadata:
      labels:
        app: crs-converter-gke
        version: v2
    spec:
      containers:
        - name: crs-converter
          image: "{{ .Values.image.crs-converter.repository }}:{{ .Values.image.crs-converter.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: os-service-config
          env:
            - name: ENTITLEMENT_URL
              value: "{{ .Values.service.entitlement.url }}"
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
