apiVersion: v1
kind: Service
metadata:
  name: crs-converter-gke
  labels:
    app: crs-converter-gke
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.targetPort }}
      name: https
  selector:
    app: crs-converter-gke
