LOG_PREFIX=crs-conversion

server.servlet.contextPath=/api/crs/converter/
server.servlet.application-display-name=CRS Converter Service
server.error.whitelabel.enabled=false

logging.level.org.springframework=${LOG_LEVEL:INFO}
server.port=8080

spring.main.allow-bean-definition-overriding=true
spring.mvc.throw-exception-if-no-handler-found=true

JAVA_HEAP_OPTS=-Xms4096M -Xmx4096M
JAVA_GC_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45

# [Required] URL of the Entitlements Service
ENTITLEMENTS_HOST=http://entitlements
ENTITLEMENTS_PATH=/api/entitlements/v2/
ENTITLEMENTS_API=${ENTITLEMENTS_HOST}${ENTITLEMENTS_PATH}
osdu.entitlement.url=${ENTITLEMENTS_API}

STORAGE_HOST=http://storage
STORAGE_PATH=/api/storage/v2
STORAGE_API=${STORAGE_HOST}${STORAGE_PATH}
osdu.storage.url=${STORAGE_API}

#Health checks
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE:/}
management.endpoints.web.exposure.include=health
management.health.probes.enabled=true