variables:
  OSDU_GCP_SERVICE: crs-conversion
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/crs_converter_test_gcp
  OSDU_GCP_HELM_DEPLOYMENT_DIR: "devops/gcp/deploy"
  OSDU_GCP_HELM_CONFIG_DIR: "devops/gcp/configmap"
  OSDU_GCP_HELM_NAMESPACE: default
  OSDU_GCP_HELM_CONFIG_SERVICE: crs-conversion-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: crs-conversion-deploy
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: >
    --set data.sis_data=$OSDU_GCP_SIS_DATA 
    --set data.audiences=$GOOGLE_AUDIENCE 
    --set data.partition_api=$OSDU_GCP_PARTITION_API 
    --set data.entitlements_api=$OSDU_GCP_AUTHORIZE_API 
    --set data.log_level=INFO
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.sis_data=$OSDU_GCP_SIS_DATA 
    --set data.audiences=$GOOGLE_AUDIENCE 
    --set data.partition_api=$OSDU_GCP_PARTITION_API 
    --set data.entitlements_api=$OSDU_GCP_AUTHORIZE_API 
    --set data.log_level=INFO
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA 
    --set data.serviceAccountName=crs-conversion-k8s 
    --set conf.app_name=$OSDU_GCP_SERVICE
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"

osdu-gcp-containerize-gitlab:
  variables:
    BUILD_PATH: "provider/crs-converter-$OSDU_GCP_VENDOR/cloudbuild/Dockerfile.cloudbuild"

osdu-gcp-containerize-gcr:
  variables:
    BUILD_PATH: "provider/crs-converter-$OSDU_GCP_VENDOR/cloudbuild/Dockerfile.cloudbuild"

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CONVERTER_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CONVERTER_HOSTNAME
