variables:
  BUILD_PATH: "provider/crs-converter-$OSDU_GCP_VENDOR/cloudbuild/Dockerfile.cloudbuild"
  OSDU_GCP_SERVICE: crs-conversion
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/crs_converter_test_gcp

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CONVERTER_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CONVERTER_HOSTNAME
