variables:
  SIS_DATA: $CI_PROJECT_DIR/apachesis_setup/SIS_DATA
  
  AZURE_SERVICE: crs_converter
  AZURE_BUILD_SUBDIR: provider/crs-converter-azure/crs-converter-aks
  AZURE_TEST_SUBDIR: testing/crs_converter_test_azure


  AWS_BUILD_SUBDIR: provider/crs-converter-aws/build-aws
  AWS_TEST_SUBDIR: testing/crs_converter_test_aws
  AWS_SERVICE: crs-conversion
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python

  IBM_BUILD_SUBDIR: provider/crs-converter-ibm/crs-converter-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/crs_converter_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py

  OSDU_GCP_ENVIRONMENT: osdu-gcp
  OSDU_GCP_SERVICE: crs-converter
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: crs-converter
  OSDU_GCP_SIS_DATA: /crs-converter/apachesis_setup/SIS_DATA
  OSDU_GCP_ENV_VARS: OSDU_ENTITLEMENT_URL=$OSDU_GCP_ENTITLEMENTS_URL,SIS_DATA=$OSDU_GCP_SIS_DATA
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR:  testing/crs_converter_test_gcp
  DATA_DIR: /tmp/CloudTestData
  DATA_PATTERN: Test*.0*.json
  REPORT_PATH: /tmp/CloudTestData/Report/SuiteReport.txt

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
  
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "master"
    file: "cloud-providers/osdu-gcp-cloudrun.yml"

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_CRS_CONVERTER_HOSTNAME

