# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.crs_conversion_api import CRSConversionApi


class TestCRSConversionApi(unittest.TestCase):
    """ CRSConversionApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.crs_conversion_api.CRSConversionApi()

    def tearDown(self):
        pass

    def test_convert_bin_grid(self):
        """
        Test case for convert_bin_grid

        CRS Convert service is an OSDU platform standard method for QC and conversion of Bin Grids, associated in particular with ingested seismic volumes, that describe the “real world” (Easting, Northing) of bin grid centers at (inline, crossline) local coordinates
        """
        pass

    def test_convert_geo_json(self):
        """
        Test case for convert_geo_json

        Convert a GeoJSON or AnyCrsGeoJson structure
        """
        pass

    def test_convert_point(self):
        """
        Test case for convert_point

        Convert a list of points
        """
        pass


if __name__ == '__main__':
    unittest.main()
