version: "3"
services:
  os-crs-converter-app:
    build:
      context: ../../../../
      dockerfile: provider/crs-converter-gcp/crs-converter-gke/docker/Dockerfile
      args:
        - SIS_DATA=/crs-converter/apachesis_setup/SIS_DATA
    image: gcr.io/opendes/os-crs-converter-app
    ports:
     - "8080:8080"