# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AbstractFeature(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'properties': 'PropertiesBinGridCorners',
        'geometry': 'Geometry'
    }

    attribute_map = {
        'type': 'type',
        'properties': 'properties',
        'geometry': 'geometry'
    }

    def __init__(self, type=None, properties=None, geometry=None):
        """
        AbstractFeature - a model defined in Swagger
        """

        self._type = None
        self._properties = None
        self._geometry = None

        if type is not None:
          self.type = type
        if properties is not None:
          self.properties = properties
        if geometry is not None:
          self.geometry = geometry

    @property
    def type(self):
        """
        Gets the type of this AbstractFeature.

        :return: The type of this AbstractFeature.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AbstractFeature.

        :param type: The type of this AbstractFeature.
        :type: str
        """

        self._type = type

    @property
    def properties(self):
        """
        Gets the properties of this AbstractFeature.

        :return: The properties of this AbstractFeature.
        :rtype: PropertiesBinGridCorners
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """
        Sets the properties of this AbstractFeature.

        :param properties: The properties of this AbstractFeature.
        :type: PropertiesBinGridCorners
        """

        self._properties = properties

    @property
    def geometry(self):
        """
        Gets the geometry of this AbstractFeature.

        :return: The geometry of this AbstractFeature.
        :rtype: Geometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """
        Sets the geometry of this AbstractFeature.

        :param geometry: The geometry of this AbstractFeature.
        :type: Geometry
        """

        self._geometry = geometry

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AbstractFeature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
