# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AbstractSpatialLocation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'spatial_location_coordinates_date': 'str',
        'quantitative_accuracy_band_id': 'str',
        'qualitative_spatial_accuracy_type_id': 'str',
        'coordinate_quality_check_performed_by': 'str',
        'coordinate_quality_check_date_time': 'str',
        'coordinate_quality_check_remarks': 'list[str]',
        'applied_operations': 'list[str]',
        'spatial_parameter_type_id': 'str',
        'spatial_geometry_type_id': 'str',
        'as_ingested_coordinates': 'AbstractAnyCrsFeatureCollection',
        'wgs84_coordinates': 'AbstractFeatureCollection'
    }

    attribute_map = {
        'spatial_location_coordinates_date': 'SpatialLocationCoordinatesDate',
        'quantitative_accuracy_band_id': 'QuantitativeAccuracyBandID',
        'qualitative_spatial_accuracy_type_id': 'QualitativeSpatialAccuracyTypeID',
        'coordinate_quality_check_performed_by': 'CoordinateQualityCheckPerformedBy',
        'coordinate_quality_check_date_time': 'CoordinateQualityCheckDateTime',
        'coordinate_quality_check_remarks': 'CoordinateQualityCheckRemarks',
        'applied_operations': 'AppliedOperations',
        'spatial_parameter_type_id': 'SpatialParameterTypeID',
        'spatial_geometry_type_id': 'SpatialGeometryTypeID',
        'as_ingested_coordinates': 'AsIngestedCoordinates',
        'wgs84_coordinates': 'Wgs84Coordinates'
    }

    def __init__(self, spatial_location_coordinates_date=None, quantitative_accuracy_band_id=None, qualitative_spatial_accuracy_type_id=None, coordinate_quality_check_performed_by=None, coordinate_quality_check_date_time=None, coordinate_quality_check_remarks=None, applied_operations=None, spatial_parameter_type_id=None, spatial_geometry_type_id=None, as_ingested_coordinates=None, wgs84_coordinates=None):
        """
        AbstractSpatialLocation - a model defined in Swagger
        """

        self._spatial_location_coordinates_date = None
        self._quantitative_accuracy_band_id = None
        self._qualitative_spatial_accuracy_type_id = None
        self._coordinate_quality_check_performed_by = None
        self._coordinate_quality_check_date_time = None
        self._coordinate_quality_check_remarks = None
        self._applied_operations = None
        self._spatial_parameter_type_id = None
        self._spatial_geometry_type_id = None
        self._as_ingested_coordinates = None
        self._wgs84_coordinates = None

        if spatial_location_coordinates_date is not None:
          self.spatial_location_coordinates_date = spatial_location_coordinates_date
        if quantitative_accuracy_band_id is not None:
          self.quantitative_accuracy_band_id = quantitative_accuracy_band_id
        if qualitative_spatial_accuracy_type_id is not None:
          self.qualitative_spatial_accuracy_type_id = qualitative_spatial_accuracy_type_id
        if coordinate_quality_check_performed_by is not None:
          self.coordinate_quality_check_performed_by = coordinate_quality_check_performed_by
        if coordinate_quality_check_date_time is not None:
          self.coordinate_quality_check_date_time = coordinate_quality_check_date_time
        if coordinate_quality_check_remarks is not None:
          self.coordinate_quality_check_remarks = coordinate_quality_check_remarks
        if applied_operations is not None:
          self.applied_operations = applied_operations
        if spatial_parameter_type_id is not None:
          self.spatial_parameter_type_id = spatial_parameter_type_id
        if spatial_geometry_type_id is not None:
          self.spatial_geometry_type_id = spatial_geometry_type_id
        if as_ingested_coordinates is not None:
          self.as_ingested_coordinates = as_ingested_coordinates
        if wgs84_coordinates is not None:
          self.wgs84_coordinates = wgs84_coordinates

    @property
    def spatial_location_coordinates_date(self):
        """
        Gets the spatial_location_coordinates_date of this AbstractSpatialLocation.

        :return: The spatial_location_coordinates_date of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._spatial_location_coordinates_date

    @spatial_location_coordinates_date.setter
    def spatial_location_coordinates_date(self, spatial_location_coordinates_date):
        """
        Sets the spatial_location_coordinates_date of this AbstractSpatialLocation.

        :param spatial_location_coordinates_date: The spatial_location_coordinates_date of this AbstractSpatialLocation.
        :type: str
        """

        self._spatial_location_coordinates_date = spatial_location_coordinates_date

    @property
    def quantitative_accuracy_band_id(self):
        """
        Gets the quantitative_accuracy_band_id of this AbstractSpatialLocation.

        :return: The quantitative_accuracy_band_id of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._quantitative_accuracy_band_id

    @quantitative_accuracy_band_id.setter
    def quantitative_accuracy_band_id(self, quantitative_accuracy_band_id):
        """
        Sets the quantitative_accuracy_band_id of this AbstractSpatialLocation.

        :param quantitative_accuracy_band_id: The quantitative_accuracy_band_id of this AbstractSpatialLocation.
        :type: str
        """

        self._quantitative_accuracy_band_id = quantitative_accuracy_band_id

    @property
    def qualitative_spatial_accuracy_type_id(self):
        """
        Gets the qualitative_spatial_accuracy_type_id of this AbstractSpatialLocation.

        :return: The qualitative_spatial_accuracy_type_id of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._qualitative_spatial_accuracy_type_id

    @qualitative_spatial_accuracy_type_id.setter
    def qualitative_spatial_accuracy_type_id(self, qualitative_spatial_accuracy_type_id):
        """
        Sets the qualitative_spatial_accuracy_type_id of this AbstractSpatialLocation.

        :param qualitative_spatial_accuracy_type_id: The qualitative_spatial_accuracy_type_id of this AbstractSpatialLocation.
        :type: str
        """

        self._qualitative_spatial_accuracy_type_id = qualitative_spatial_accuracy_type_id

    @property
    def coordinate_quality_check_performed_by(self):
        """
        Gets the coordinate_quality_check_performed_by of this AbstractSpatialLocation.

        :return: The coordinate_quality_check_performed_by of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._coordinate_quality_check_performed_by

    @coordinate_quality_check_performed_by.setter
    def coordinate_quality_check_performed_by(self, coordinate_quality_check_performed_by):
        """
        Sets the coordinate_quality_check_performed_by of this AbstractSpatialLocation.

        :param coordinate_quality_check_performed_by: The coordinate_quality_check_performed_by of this AbstractSpatialLocation.
        :type: str
        """

        self._coordinate_quality_check_performed_by = coordinate_quality_check_performed_by

    @property
    def coordinate_quality_check_date_time(self):
        """
        Gets the coordinate_quality_check_date_time of this AbstractSpatialLocation.

        :return: The coordinate_quality_check_date_time of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._coordinate_quality_check_date_time

    @coordinate_quality_check_date_time.setter
    def coordinate_quality_check_date_time(self, coordinate_quality_check_date_time):
        """
        Sets the coordinate_quality_check_date_time of this AbstractSpatialLocation.

        :param coordinate_quality_check_date_time: The coordinate_quality_check_date_time of this AbstractSpatialLocation.
        :type: str
        """

        self._coordinate_quality_check_date_time = coordinate_quality_check_date_time

    @property
    def coordinate_quality_check_remarks(self):
        """
        Gets the coordinate_quality_check_remarks of this AbstractSpatialLocation.

        :return: The coordinate_quality_check_remarks of this AbstractSpatialLocation.
        :rtype: list[str]
        """
        return self._coordinate_quality_check_remarks

    @coordinate_quality_check_remarks.setter
    def coordinate_quality_check_remarks(self, coordinate_quality_check_remarks):
        """
        Sets the coordinate_quality_check_remarks of this AbstractSpatialLocation.

        :param coordinate_quality_check_remarks: The coordinate_quality_check_remarks of this AbstractSpatialLocation.
        :type: list[str]
        """

        self._coordinate_quality_check_remarks = coordinate_quality_check_remarks

    @property
    def applied_operations(self):
        """
        Gets the applied_operations of this AbstractSpatialLocation.

        :return: The applied_operations of this AbstractSpatialLocation.
        :rtype: list[str]
        """
        return self._applied_operations

    @applied_operations.setter
    def applied_operations(self, applied_operations):
        """
        Sets the applied_operations of this AbstractSpatialLocation.

        :param applied_operations: The applied_operations of this AbstractSpatialLocation.
        :type: list[str]
        """

        self._applied_operations = applied_operations

    @property
    def spatial_parameter_type_id(self):
        """
        Gets the spatial_parameter_type_id of this AbstractSpatialLocation.

        :return: The spatial_parameter_type_id of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._spatial_parameter_type_id

    @spatial_parameter_type_id.setter
    def spatial_parameter_type_id(self, spatial_parameter_type_id):
        """
        Sets the spatial_parameter_type_id of this AbstractSpatialLocation.

        :param spatial_parameter_type_id: The spatial_parameter_type_id of this AbstractSpatialLocation.
        :type: str
        """

        self._spatial_parameter_type_id = spatial_parameter_type_id

    @property
    def spatial_geometry_type_id(self):
        """
        Gets the spatial_geometry_type_id of this AbstractSpatialLocation.

        :return: The spatial_geometry_type_id of this AbstractSpatialLocation.
        :rtype: str
        """
        return self._spatial_geometry_type_id

    @spatial_geometry_type_id.setter
    def spatial_geometry_type_id(self, spatial_geometry_type_id):
        """
        Sets the spatial_geometry_type_id of this AbstractSpatialLocation.

        :param spatial_geometry_type_id: The spatial_geometry_type_id of this AbstractSpatialLocation.
        :type: str
        """

        self._spatial_geometry_type_id = spatial_geometry_type_id

    @property
    def as_ingested_coordinates(self):
        """
        Gets the as_ingested_coordinates of this AbstractSpatialLocation.

        :return: The as_ingested_coordinates of this AbstractSpatialLocation.
        :rtype: AbstractAnyCrsFeatureCollection
        """
        return self._as_ingested_coordinates

    @as_ingested_coordinates.setter
    def as_ingested_coordinates(self, as_ingested_coordinates):
        """
        Sets the as_ingested_coordinates of this AbstractSpatialLocation.

        :param as_ingested_coordinates: The as_ingested_coordinates of this AbstractSpatialLocation.
        :type: AbstractAnyCrsFeatureCollection
        """

        self._as_ingested_coordinates = as_ingested_coordinates

    @property
    def wgs84_coordinates(self):
        """
        Gets the wgs84_coordinates of this AbstractSpatialLocation.

        :return: The wgs84_coordinates of this AbstractSpatialLocation.
        :rtype: AbstractFeatureCollection
        """
        return self._wgs84_coordinates

    @wgs84_coordinates.setter
    def wgs84_coordinates(self, wgs84_coordinates):
        """
        Sets the wgs84_coordinates of this AbstractSpatialLocation.

        :param wgs84_coordinates: The wgs84_coordinates of this AbstractSpatialLocation.
        :type: AbstractFeatureCollection
        """

        self._wgs84_coordinates = wgs84_coordinates

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AbstractSpatialLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
