# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConvertBinGridResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_mis_location': 'MaxMisLocation',
        'out_bin_grid': 'AbstractBinGrid',
        'applied_operations': 'list[str]'
    }

    attribute_map = {
        'max_mis_location': 'maxMisLocation',
        'out_bin_grid': 'outBinGrid',
        'applied_operations': 'AppliedOperations'
    }

    def __init__(self, max_mis_location=None, out_bin_grid=None, applied_operations=None):
        """
        ConvertBinGridResponse - a model defined in Swagger
        """

        self._max_mis_location = None
        self._out_bin_grid = None
        self._applied_operations = None

        if max_mis_location is not None:
          self.max_mis_location = max_mis_location
        if out_bin_grid is not None:
          self.out_bin_grid = out_bin_grid
        if applied_operations is not None:
          self.applied_operations = applied_operations

    @property
    def max_mis_location(self):
        """
        Gets the max_mis_location of this ConvertBinGridResponse.

        :return: The max_mis_location of this ConvertBinGridResponse.
        :rtype: MaxMisLocation
        """
        return self._max_mis_location

    @max_mis_location.setter
    def max_mis_location(self, max_mis_location):
        """
        Sets the max_mis_location of this ConvertBinGridResponse.

        :param max_mis_location: The max_mis_location of this ConvertBinGridResponse.
        :type: MaxMisLocation
        """

        self._max_mis_location = max_mis_location

    @property
    def out_bin_grid(self):
        """
        Gets the out_bin_grid of this ConvertBinGridResponse.

        :return: The out_bin_grid of this ConvertBinGridResponse.
        :rtype: AbstractBinGrid
        """
        return self._out_bin_grid

    @out_bin_grid.setter
    def out_bin_grid(self, out_bin_grid):
        """
        Sets the out_bin_grid of this ConvertBinGridResponse.

        :param out_bin_grid: The out_bin_grid of this ConvertBinGridResponse.
        :type: AbstractBinGrid
        """

        self._out_bin_grid = out_bin_grid

    @property
    def applied_operations(self):
        """
        Gets the applied_operations of this ConvertBinGridResponse.

        :return: The applied_operations of this ConvertBinGridResponse.
        :rtype: list[str]
        """
        return self._applied_operations

    @applied_operations.setter
    def applied_operations(self, applied_operations):
        """
        Sets the applied_operations of this ConvertBinGridResponse.

        :param applied_operations: The applied_operations of this ConvertBinGridResponse.
        :type: list[str]
        """

        self._applied_operations = applied_operations

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConvertBinGridResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
