# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConvertBinGridRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to_crs': 'str',
        'in_bin_grid': 'AbstractBinGrid'
    }

    attribute_map = {
        'to_crs': 'toCRS',
        'in_bin_grid': 'inBinGrid'
    }

    def __init__(self, to_crs=None, in_bin_grid=None):
        """
        ConvertBinGridRequest - a model defined in Swagger
        """

        self._to_crs = None
        self._in_bin_grid = None

        if to_crs is not None:
          self.to_crs = to_crs
        if in_bin_grid is not None:
          self.in_bin_grid = in_bin_grid

    @property
    def to_crs(self):
        """
        Gets the to_crs of this ConvertBinGridRequest.

        :return: The to_crs of this ConvertBinGridRequest.
        :rtype: str
        """
        return self._to_crs

    @to_crs.setter
    def to_crs(self, to_crs):
        """
        Sets the to_crs of this ConvertBinGridRequest.

        :param to_crs: The to_crs of this ConvertBinGridRequest.
        :type: str
        """

        self._to_crs = to_crs

    @property
    def in_bin_grid(self):
        """
        Gets the in_bin_grid of this ConvertBinGridRequest.

        :return: The in_bin_grid of this ConvertBinGridRequest.
        :rtype: AbstractBinGrid
        """
        return self._in_bin_grid

    @in_bin_grid.setter
    def in_bin_grid(self, in_bin_grid):
        """
        Sets the in_bin_grid of this ConvertBinGridRequest.

        :param in_bin_grid: The in_bin_grid of this ConvertBinGridRequest.
        :type: AbstractBinGrid
        """

        self._in_bin_grid = in_bin_grid

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConvertBinGridRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
