# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MaxMisLocation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'd_i': 'float',
        'd_j': 'float'
    }

    attribute_map = {
        'd_i': 'dI',
        'd_j': 'dJ'
    }

    def __init__(self, d_i=None, d_j=None):
        """
        MaxMisLocation - a model defined in Swagger
        """

        self._d_i = None
        self._d_j = None

        if d_i is not None:
          self.d_i = d_i
        if d_j is not None:
          self.d_j = d_j

    @property
    def d_i(self):
        """
        Gets the d_i of this MaxMisLocation.

        :return: The d_i of this MaxMisLocation.
        :rtype: float
        """
        return self._d_i

    @d_i.setter
    def d_i(self, d_i):
        """
        Sets the d_i of this MaxMisLocation.

        :param d_i: The d_i of this MaxMisLocation.
        :type: float
        """

        self._d_i = d_i

    @property
    def d_j(self):
        """
        Gets the d_j of this MaxMisLocation.

        :return: The d_j of this MaxMisLocation.
        :rtype: float
        """
        return self._d_j

    @d_j.setter
    def d_j(self, d_j):
        """
        Sets the d_j of this MaxMisLocation.

        :param d_j: The d_j of this MaxMisLocation.
        :type: float
        """

        self._d_j = d_j

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MaxMisLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
