# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PropertiesBinGridCorners(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kind': 'str',
        'point_properties': 'list[PointProperties]'
    }

    attribute_map = {
        'kind': 'Kind',
        'point_properties': 'PointProperties'
    }

    def __init__(self, kind=None, point_properties=None):
        """
        PropertiesBinGridCorners - a model defined in Swagger
        """

        self._kind = None
        self._point_properties = None

        if kind is not None:
          self.kind = kind
        if point_properties is not None:
          self.point_properties = point_properties

    @property
    def kind(self):
        """
        Gets the kind of this PropertiesBinGridCorners.

        :return: The kind of this PropertiesBinGridCorners.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """
        Sets the kind of this PropertiesBinGridCorners.

        :param kind: The kind of this PropertiesBinGridCorners.
        :type: str
        """

        self._kind = kind

    @property
    def point_properties(self):
        """
        Gets the point_properties of this PropertiesBinGridCorners.

        :return: The point_properties of this PropertiesBinGridCorners.
        :rtype: list[PointProperties]
        """
        return self._point_properties

    @point_properties.setter
    def point_properties(self, point_properties):
        """
        Sets the point_properties of this PropertiesBinGridCorners.

        :param point_properties: The point_properties of this PropertiesBinGridCorners.
        :type: list[PointProperties]
        """

        self._point_properties = point_properties

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PropertiesBinGridCorners):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
