# Default values for crs-conversion-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  logLevel: "ERROR"
  tier: ""
  autoscaling: true

data:
  #configmaps
  logLevel: ""
  sisData: "/crs-converter/apachesis_setup/SIS_DATA"
  storageHost: "http://storage"
  entitlementsHost: "http://entitlements"
  #deployments
  requestsCpu: "5m"
  requestsMemory: "230Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "crs-conversion"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "crs-conversion-config"
  appName: "crs-conversion"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue"
  targetValue: 195  # 115*0.85*2 rps
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 115
  tokensPerFill: 115
  fillInterval: "1s"
