# Default values for crs-conversion-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false

data:
  #configmaps
  logLevel: "ERROR"
  sisData: "/crs-converter/apachesis_setup/SIS_DATA"
  storageHost: "http://storage"
  entitlementsHost: "http://entitlements"
  #deployments
  requestsCpu: "5m"
  requestsMemory: "230Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "crs-conversion"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "crs-conversion-config"
  appName: "crs-conversion"

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"
