apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
#log-and-common
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  logging.level.org.opengroup.osdu: "{{ .Values.data.loggingLevelOsdu }}"
  logging.level.org.springframework.web: "{{ .Values.data.loggingLevelSpring }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  server.servlet.context-path: "{{ .Values.data.contextPath }}"
  server.port: "{{ .Values.data.serverPort }}"
  spring.main.allow-bean-definition-overriding: "{{ .Values.data.beanDefOverriding }}" 

#Authorization  
  osdu.entitlement.url: "http://{{ .Release.Name }}-ibm-entitlement-deploy:8080/api/entitlements/v2"
  SIS_DATA: /home/jboss/data/SIS_DATA 
