{{- template "common.serviceparameters" (list . "os-crs-conversion.serviceparameters") -}}
{{- define "os-crs-conversion.serviceparameters" -}}
## Define overrides for the service parameters here
{{- end -}}