#Manage common SpringDoc and OpenAPI related properties

#SpringDoc related properties
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.displayOperationId=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.groups-order=DESC

#OpenAPI 3.0 - CRS Conversion properties
api.title=CRS Conversion Service
api.description=Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.
api.version=1.0.0
api.contact.name=OSDU Data Platform Team
api.contact.email=dps@OSDU.org
api.license.name=Apache 2.0
api.license.url=https://www.apache.org/licenses/LICENSE-2.0.html
api.server.url=${server.servlet.contextPath}

#Info & Health API related properties
infoApi.info.summary=info
infoApi.info.description=For deployment available public `/info` endpoint, which provides build and git related information.
healthCheckApi.livenessCheck.summary=Liveness Check endpoint
healthCheckApi.livenessCheck.description=For deployment available public `/liveness_check` endpoint, which provides `CRS Conversion Service is alive` message.
healthCheckApi.readinessCheck.summary=Readiness Check endpoint
healthCheckApi.readinessCheck.description=For deployment available public `/readiness_check` endpoint, which provides `CRS Conversion Service is ready` message.
CrsConverterApi.convertPoint.summary=Convert a list of points
CrsConverterApi.convertPoint.description=Convert a list of points
CrsConverterApi.geo_json_convert.summary=Convert a GeoJSON or AnyCrsGeoJson structure
CrsConverterApi.geo_json_convert.description=Convert a GeoJSON or AnyCrsGeoJson structure to a specified target CRS. GeoJSON is declared - by definition - to be in the context of WGS 84.
CrsConverterApi.convertTrajectory.summary=Convert trajectory stations
CrsConverterApi.convertTrajectory.description=Convert a list of trajectory stations, given the unit and spatial context and a reference point in 3D where MD==0.
CrsConverterApi.BinGrid.summary=CRS Convert service is an OSDU platform standard method for QC and conversion of Bin Grids, associated in particular with ingested seismic volumes, that describe the `real world` (Easting, Northing) of bin grid centers at (inline, crossline) local coordinates
CrsConverterApi.BinGrid.description=QC check of the `squareness` of a Bin Grid defined using 4 corner points.\n \
                                    + Coordinate conversion of a Bin Grid to a new CRS and `square it up` (if target CRS is same as original CRS then conversion is omitted, and the squareness test is done in the original CRS).\n \
                                    + Calculate derived P6 parameters from the input 4 corners.\n \
                                    + Calculate WGS 84 coordinates at the corners\n \
                                    + Returns converted Bin Grid and a QC of squareness of the bin grid

CrsConverterApiV4.convertPoint.summary=Convert trajectory stations
CrsConverterApiV4.convertPoint.description=Convert a list of trajectory stations, given the unit and spatial context and a reference point in 3D where MD==0.