variables:
  CIMPL_SERVICE: crs-conversion
  CIMPL_INT_TEST_TYPE: python
  CIMPL_BAREMETAL_PYTHON_INT_TEST_SUBDIR: testing/crs_converter_test_baremetal
  CIMPL_BUILD_PATH: "crs-converter-core-plus/build/Dockerfile"

cimpl-containerize-gitlab:
  needs:
    - "compile-and-unit-test"

