parameters:
  environments: []

stages:
  - ${{ each environment in parameters.environments }}:
    - stage: 'Build_${{ environment.name }}'

      variables:
      - group: 'Azure Target Env - ${{environment.name}}'
      - group: 'Azure Target Env Secrets - ${{environment.name}}'
      - name: tag
        value: 'v2'

      jobs:
        - job: MavenPackageAndPublishArtifacts
          displayName: Maven Package and Publish Artifacts
          pool: $(AGENT_POOL)

          steps:
          - ${{ if eq(environment.name, 'devint') }}:
            - task: Maven@3
              displayName: 'Maven: build, and test all modules'
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'install'
                options: '--settings ./maven/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -Dclient-id=$(aad_client_id) '
                testResultsFiles: '**/*/TEST-*.xml'
                codeCoverageToolOption: JaCoCo
            - task: Maven@3
              displayName: 'Maven, crs-converter-aks: test, code coverage'
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'test'
                options: '--settings ./maven/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -Dclient-id=$(aad_client_id)'
                testResultsFiles: '**/*/TEST-*.xml'
                codeCoverageToolOption: JaCoCo

            - bash: |
                #!/bin/bash
                set -e
                docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
                docker build -t $(dockerId).azurecr.io/$(imageName):$(tag) --build-arg CRS_CONVERTER_JAR_PATH=$(crsConverterJarPath) .
                echo 'Image done.'

                docker push $(dockerId).azurecr.io/$(imageName)
                docker tag $(dockerId).azurecr.io/$(imageName):$(tag) $(dockerId).azurecr.io/$(imageName):latest

                echo 'Added $(dockerId).azurecr.io/$(imageName):latest tag to $(dockerId).azurecr.io/$(imageName):$(tag)'
                docker push $(dockerId).azurecr.io/$(imageName):$(tag)

                echo 'Pushed $(dockerId).azurecr.io/$(imageName):$(tag)'
                docker push $(dockerId).azurecr.io/$(imageName):latest
                echo 'Pushed $(dockerId).azurecr.io/$(imageName):latest'
              displayName: 'build and upload docker image $(dockerId).azurecr.io/$(imageName)'
          - bash: |
              #!/bin/bash
              set -e
              pushd provider/crs-converter-azure/crs-converter-aks/crs-converter-aks
              sed "s|ENTITLEMENT_URL|$(ENTITLEMENT_URL)|g" values.yaml.tmpl > values.yaml
              sed -i "s|client-id|$(AZURE_AD_APP_RESOURCE_ID)|g" values.yaml
              echo "Content:"
              cat values.yaml
              echo ""              
              popd
            displayName: 'generate values.yaml with actual variables: $(ENTITLEMENT_URL) ${client-id}'
          - bash: |
              #!/bin/bash
              set -e
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
              chmod 700 get_helm.sh
              ./get_helm.sh
              # package helm chart
              helm package provider/crs-converter-azure/crs-converter-aks/crs-converter-aks --version 0.0.1 --destination '$(build.artifactstagingdirectory)'
            displayName: 'install helm 3 and package helm chart'
          - bash: |
              #!/bin/bash
              set -e
              # Zip integration tests and upload it as artifact
              zip -r testing.zip testing
              cp testing.zip $(build.artifactstagingdirectory)   
            displayName: 'Zip integration tests and upload it as artifact'
          - upload: $(Build.ArtifactStagingDirectory)
            artifact: drop_${{environment.name}}

    - stage: Deploy_${{environment.name}}
      dependsOn: 'Build_${{ environment.name }}'
      condition: succeeded()

      variables:
      - group: 'Azure Target Env - ${{environment.name}}'
      - group: 'Azure Target Env Secrets - ${{environment.name}}'
      - group: 'AKS Target Env - ${{ environment.name }}'
      - name: tag
        value: 'v2'

      jobs:
        - deployment: DeployLinuxWebApp
          displayName: Deploy Linux Web App
          environment: ${{ environment.name }}
          pool: $(AGENT_POOL)

          strategy:
            runOnce:
              deploy:
                steps:
                - task: DownloadSecureFile@1
                  name: kubeConfig
                  inputs:
                    secureFile: 'kubeconfig-${{environment.name}}'
                - task: KubectlInstaller@0
                  displayName: 'Install Kubectl latest'
                - bash: |
                    #!/bin/bash
                    set -e
                    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
                    chmod 700 get_helm.sh
                    ./get_helm.sh                 
                  displayName: 'Install helm 3'
                - task: HelmDeploy@0
                  displayName: 'helm upgrade'
                  inputs:
                    connectionType: Kubernetes Service Connection
                    kubernetesServiceEndpoint: ${{ environment.kubeconfig }}
                    command: upgrade
                    arguments: '--wait'
                    chartType: FilePath
                    chartPath: '$(Pipeline.Workspace)/drop_${{environment.name}}/crs-converter-aks-0.0.1.tgz'
                    releaseName: 'crs-converter-aks'

                - bash: |
                    #!/bin/bash
                    set -e
                    kubectl --kubeconfig $(kubeConfig.secureFilePath) rollout restart deployment/crs-converter-aks
                  displayName: 'kubectl rollout restart deployment/crs-converter-aks'

                - ${{ if or(eq(environment.name, 'devint'), eq(environment.name, 'qa')) }}:
                  - bash: |
                      #!/bin/bash
                      set -e

                      echo "Current working directory: "
                      pwd
                      echo "Contents of $(Pipeline.Workspace)/drop_${{environment.name}}: "
                      ls -al $(Pipeline.Workspace)/drop_${{environment.name}}
                      # Unzip integration tests
                      unzip $(Pipeline.Workspace)/drop_${{environment.name}}/testing.zip -d $(Pipeline.Workspace)/drop_${{environment.name}}/
                      chmod +x $(Pipeline.Workspace)/drop_${{environment.name}}/testing/crs_converter_test_sauth/run-integration-tests.sh

                      printf 'waiting for service to be ready:'
                      sleep 10
                      attempt_counter=0
                      max_attempts=60
                      until [ $(curl -s -o /dev/null -w "%{http_code}" https://$(VIRTUAL_SERVICE_HOST_NAME)/api/crs/converter/_ah/liveness_check) -eq 200 ]; do
                      if [ ${attempt_counter} -ge ${max_attempts} ]; then
                          echo "Service is not available, please check the deployment"
                          exit 1
                      fi
                      printf '.'
                      attempt_counter=$(($attempt_counter+1))
                      sleep 2
                      done

                    displayName: 'Unzip integration tests and Wait for service to be ready'
                  - task: Bash@3
                    displayName: 'Run integration tests'
                    inputs:
                      targetType: filePath
                      filePath: '$(Pipeline.Workspace)/drop_${{environment.name}}/testing/crs_converter_test_sauth/run-integration-tests.sh'
                      arguments: '$(AUTH_SECRET) $(AUTH_SERVICE_TOKEN_X_API_KEY)'
                      workingDirectory: '$(Pipeline.Workspace)/drop_${{environment.name}}/testing/crs_converter_test_sauth'
