# Default values for crs-conversion-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  log_level: "INFO"
  entitlements_api: "http://entitlements/api/entitlements/v2/"
  sis_data: "/crs-converter/apachesis_setup/SIS_DATA"
  storageApi: "http://storage/api/storage/v2"

conf:
  configmap: "crs-conversion-config"
  app_name: "crs-conversion"
