---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibm-crs-conversion-deploy.fullname" . }}
  labels:
    {{- include "ibm-crs-conversion-deploy.labels" . | nindent 4 }}
data:
  crs-conversion_post.sh: |
    {{- tpl (.Files.Get "files/crs-conversion_post.sh" ) . | nindent 4 }}