apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibm-crs-conversion-deploy.fullname" . }}
  labels:
    {{- include "ibm-crs-conversion-deploy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ibm-crs-conversion-deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "ibm-crs-conversion-deploy.selectorLabels" . | nindent 8 }}
        sidecar.istio.io/inject: "{{ .Values.sidecarIstioInjected }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ibm-crs-conversion-deploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: sis-data
          persistentVolumeClaim:
            claimName: sis-data           
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-myservice
          command:
            - sh
            - '-c'
            - 'id; chown 185:185 /home/jboss/data;'
          securityContext: {}
          imagePullPolicy: Always
          volumeMounts:
            - name: sis-data
              mountPath: /home/jboss/data
          terminationMessagePolicy: File
          image: busybox:stable
          terminationMessagePath: /dev/termination-log            
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: crs-conversion-config
          volumeMounts:
            - name: sis-data
              mountPath: /home/jboss/data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}            

