apiVersion: batch/v1
kind: Job
metadata:
  name: crs-setup-job
  labels:
    {{- include "ibm-crs-conversion-deploy.labels" . | nindent 4 }}-setup-job	
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      activeDeadlineSeconds: 600  
      containers:
        - image: {{ .Values.jobimage.repository }}:{{ .Values.jobimage.tag }}
          env:
            - name: RELEASE_NAME 
              value: {{ .Release.Name }}
            - name: RELEASE_NAMESPACE 
              value: {{ .Release.Namespace }} 
          command: ['sh', '-c', './scripts/crs-conversion_post.sh']
          imagePullPolicy: Always
          name: {{ include "ibm-crs-conversion-deploy.fullname" . }}
          volumeMounts:
            - mountPath: "/scripts"
              name: projected-scripts
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ include "ibm-crs-conversion-deploy.serviceAccountName" . }}
      serviceAccountName: {{ include "ibm-crs-conversion-deploy.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      volumes:
        -  
          name: projected-scripts
          projected:
            defaultMode: 0755
            sources:
              - configMap:
                  name: {{ include "ibm-crs-conversion-deploy.fullname" . }}                        
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ include "ibm-crs-conversion-deploy.serviceAccountName" . }}
      serviceAccountName: {{ include "ibm-crs-conversion-deploy.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30            	
