{{ if .Values.persistentvolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sis-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageclass.file_storage }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumeHandle }}
{{ end }}
