kind: PersistentVolumeClaim
apiVersion : v1
metadata:
  name: sis-data
  namespace: {{ .Release.Namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storageclass.file_storage }}
