apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  SIS_DATA: "{{ .Values.data.sisData }}"
  ENTITLEMENTS_HOST: "{{ .Values.data.entitlementsHost }}"
  OSDU_STORAGE_URL: "{{ .Values.data.storageHost }}"
