# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .convert_trajectory_request import ConvertTrajectoryRequest
from .convert_trajectory_request_v4 import ConvertTrajectoryRequestV4
from .convert_trajectory_response import ConvertTrajectoryResponse
from .convert_trajectory_response_v4 import ConvertTrajectoryResponseV4
from .error_response import ErrorResponse
from .minimum_depth_interval import MinimumDepthInterval
from .point import Point
from .scale_convergence import ScaleConvergence
from .trajectory_station_in import TrajectoryStationIn
from .trajectory_station_out import TrajectoryStationOut
