# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MinimumDepthInterval(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'md_i': 'list[float]',
        'md_interval': 'float'
    }

    attribute_map = {
        'md_i': 'md_i',
        'md_interval': 'md_interval'
    }

    def __init__(self, md_i=None, md_interval=None):
        """
        MinimumDepthInterval - a model defined in Swagger
        """

        self._md_i = None
        self._md_interval = None

        if md_i is not None:
          self.md_i = md_i
        if md_interval is not None:
          self.md_interval = md_interval

    @property
    def md_i(self):
        """
        Gets the md_i of this MinimumDepthInterval.

        :return: The md_i of this MinimumDepthInterval.
        :rtype: list[float]
        """
        return self._md_i

    @md_i.setter
    def md_i(self, md_i):
        """
        Sets the md_i of this MinimumDepthInterval.

        :param md_i: The md_i of this MinimumDepthInterval.
        :type: list[float]
        """

        self._md_i = md_i

    @property
    def md_interval(self):
        """
        Gets the md_interval of this MinimumDepthInterval.

        :return: The md_interval of this MinimumDepthInterval.
        :rtype: float
        """
        return self._md_interval

    @md_interval.setter
    def md_interval(self, md_interval):
        """
        Sets the md_interval of this MinimumDepthInterval.

        :param md_interval: The md_interval of this MinimumDepthInterval.
        :type: float
        """

        self._md_interval = md_interval

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MinimumDepthInterval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
