apiVersion: v1
kind: Service
metadata:
  name: crs-converter-aks
  labels:
    app: crs-converter-aks
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      name: http
  selector:
    app: crs-converter-aks
