LOG_PREFIX=crs-conversion

server.servlet.contextPath=/api/crs/converter/
server.servlet.application-display-name=CRS Converter Service
server.error.whitelabel.enabled=false

logging.level.org.springframework=${LOG_LEVEL:INFO}
server.port=8080

spring.main.allow-bean-definition-overriding=true
spring.mvc.throw-exception-if-no-handler-found=true

JAVA_HEAP_OPTS=-Xms4096M -Xmx4096M
JAVA_GC_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45

# [Required] URL of the Entitlements Service
osdu.entitlement.url=${ENTITLEMENT_URL}
osdu.storage.url=${STORAGE_BASE_URL:}/api/storage/v2

