# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AbstractFeatureCollection(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'features': 'list[AbstractFeature]',
        'type': 'str'
    }

    attribute_map = {
        'features': 'features',
        'type': 'Type'
    }

    def __init__(self, features=None, type=None):
        """
        AbstractFeatureCollection - a model defined in Swagger
        """

        self._features = None
        self._type = None

        if features is not None:
          self.features = features
        if type is not None:
          self.type = type

    @property
    def features(self):
        """
        Gets the features of this AbstractFeatureCollection.

        :return: The features of this AbstractFeatureCollection.
        :rtype: list[AbstractFeature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """
        Sets the features of this AbstractFeatureCollection.

        :param features: The features of this AbstractFeatureCollection.
        :type: list[AbstractFeature]
        """

        self._features = features

    @property
    def type(self):
        """
        Gets the type of this AbstractFeatureCollection.

        :return: The type of this AbstractFeatureCollection.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AbstractFeatureCollection.

        :param type: The type of this AbstractFeatureCollection.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AbstractFeatureCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
