# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AbstractAnyCrsFeatureCollection(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'persistable_reference_crs': 'str',
        'coordinate_reference_system_id': 'str',
        'type': 'str',
        'features': 'list[AbstractFeature]'
    }

    attribute_map = {
        'persistable_reference_crs': 'persistableReferenceCrs',
        'coordinate_reference_system_id': 'CoordinateReferenceSystemID',
        'type': 'type',
        'features': 'features'
    }

    def __init__(self, persistable_reference_crs=None, coordinate_reference_system_id=None, type=None, features=None):
        """
        AbstractAnyCrsFeatureCollection - a model defined in Swagger
        """

        self._persistable_reference_crs = None
        self._coordinate_reference_system_id = None
        self._type = None
        self._features = None

        if persistable_reference_crs is not None:
          self.persistable_reference_crs = persistable_reference_crs
        if coordinate_reference_system_id is not None:
          self.coordinate_reference_system_id = coordinate_reference_system_id
        if type is not None:
          self.type = type
        if features is not None:
          self.features = features

    @property
    def persistable_reference_crs(self):
        """
        Gets the persistable_reference_crs of this AbstractAnyCrsFeatureCollection.

        :return: The persistable_reference_crs of this AbstractAnyCrsFeatureCollection.
        :rtype: str
        """
        return self._persistable_reference_crs

    @persistable_reference_crs.setter
    def persistable_reference_crs(self, persistable_reference_crs):
        """
        Sets the persistable_reference_crs of this AbstractAnyCrsFeatureCollection.

        :param persistable_reference_crs: The persistable_reference_crs of this AbstractAnyCrsFeatureCollection.
        :type: str
        """

        self._persistable_reference_crs = persistable_reference_crs

    @property
    def coordinate_reference_system_id(self):
        """
        Gets the coordinate_reference_system_id of this AbstractAnyCrsFeatureCollection.

        :return: The coordinate_reference_system_id of this AbstractAnyCrsFeatureCollection.
        :rtype: str
        """
        return self._coordinate_reference_system_id

    @coordinate_reference_system_id.setter
    def coordinate_reference_system_id(self, coordinate_reference_system_id):
        """
        Sets the coordinate_reference_system_id of this AbstractAnyCrsFeatureCollection.

        :param coordinate_reference_system_id: The coordinate_reference_system_id of this AbstractAnyCrsFeatureCollection.
        :type: str
        """

        self._coordinate_reference_system_id = coordinate_reference_system_id

    @property
    def type(self):
        """
        Gets the type of this AbstractAnyCrsFeatureCollection.

        :return: The type of this AbstractAnyCrsFeatureCollection.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AbstractAnyCrsFeatureCollection.

        :param type: The type of this AbstractAnyCrsFeatureCollection.
        :type: str
        """

        self._type = type

    @property
    def features(self):
        """
        Gets the features of this AbstractAnyCrsFeatureCollection.

        :return: The features of this AbstractAnyCrsFeatureCollection.
        :rtype: list[AbstractFeature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """
        Sets the features of this AbstractAnyCrsFeatureCollection.

        :param features: The features of this AbstractAnyCrsFeatureCollection.
        :type: list[AbstractFeature]
        """

        self._features = features

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AbstractAnyCrsFeatureCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
