# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AbstractBinGrid(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bin_grid_name': 'str',
        'bin_grid_type_id': 'str',
        'source_bin_grid_id': 'int',
        'source_bin_grid_app_id': 'str',
        'coverage_percent': 'float',
        'bin_grid_definition_method_type_id': 'str',
        'p6_transformation_method': 'int',
        'p6_bin_grid_origin_i': 'float',
        'p6_bin_grid_origin_j': 'float',
        'p6_bin_grid_origin_easting': 'float',
        'p6_bin_grid_origin_northing': 'float',
        'p6_scale_factor_of_bin_grid': 'float',
        'p6_bin_width_on_iaxis': 'float',
        'p6_bin_width_on_jaxis': 'float',
        'p6_map_grid_bearing_of_bin_grid_jaxis': 'float',
        'p6_bin_node_increment_on_iaxis': 'int',
        'p6_bin_node_increment_on_jaxis': 'int',
        'abcd_bin_grid_spatial_location': 'AbstractSpatialLocation'
    }

    attribute_map = {
        'bin_grid_name': 'BinGridName',
        'bin_grid_type_id': 'BinGridTypeID',
        'source_bin_grid_id': 'SourceBinGridID',
        'source_bin_grid_app_id': 'SourceBinGridAppID',
        'coverage_percent': 'CoveragePercent',
        'bin_grid_definition_method_type_id': 'BinGridDefinitionMethodTypeID',
        'p6_transformation_method': 'P6TransformationMethod',
        'p6_bin_grid_origin_i': 'P6BinGridOriginI',
        'p6_bin_grid_origin_j': 'P6BinGridOriginJ',
        'p6_bin_grid_origin_easting': 'P6BinGridOriginEasting',
        'p6_bin_grid_origin_northing': 'P6BinGridOriginNorthing',
        'p6_scale_factor_of_bin_grid': 'P6ScaleFactorOfBinGrid',
        'p6_bin_width_on_iaxis': 'P6BinWidthOnIaxis',
        'p6_bin_width_on_jaxis': 'P6BinWidthOnJaxis',
        'p6_map_grid_bearing_of_bin_grid_jaxis': 'P6MapGridBearingOfBinGridJaxis',
        'p6_bin_node_increment_on_iaxis': 'P6BinNodeIncrementOnIaxis',
        'p6_bin_node_increment_on_jaxis': 'P6BinNodeIncrementOnJaxis',
        'abcd_bin_grid_spatial_location': 'ABCDBinGridSpatialLocation'
    }

    def __init__(self, bin_grid_name=None, bin_grid_type_id=None, source_bin_grid_id=None, source_bin_grid_app_id=None, coverage_percent=None, bin_grid_definition_method_type_id=None, p6_transformation_method=None, p6_bin_grid_origin_i=None, p6_bin_grid_origin_j=None, p6_bin_grid_origin_easting=None, p6_bin_grid_origin_northing=None, p6_scale_factor_of_bin_grid=None, p6_bin_width_on_iaxis=None, p6_bin_width_on_jaxis=None, p6_map_grid_bearing_of_bin_grid_jaxis=None, p6_bin_node_increment_on_iaxis=None, p6_bin_node_increment_on_jaxis=None, abcd_bin_grid_spatial_location=None):
        """
        AbstractBinGrid - a model defined in Swagger
        """

        self._bin_grid_name = None
        self._bin_grid_type_id = None
        self._source_bin_grid_id = None
        self._source_bin_grid_app_id = None
        self._coverage_percent = None
        self._bin_grid_definition_method_type_id = None
        self._p6_transformation_method = None
        self._p6_bin_grid_origin_i = None
        self._p6_bin_grid_origin_j = None
        self._p6_bin_grid_origin_easting = None
        self._p6_bin_grid_origin_northing = None
        self._p6_scale_factor_of_bin_grid = None
        self._p6_bin_width_on_iaxis = None
        self._p6_bin_width_on_jaxis = None
        self._p6_map_grid_bearing_of_bin_grid_jaxis = None
        self._p6_bin_node_increment_on_iaxis = None
        self._p6_bin_node_increment_on_jaxis = None
        self._abcd_bin_grid_spatial_location = None

        if bin_grid_name is not None:
          self.bin_grid_name = bin_grid_name
        if bin_grid_type_id is not None:
          self.bin_grid_type_id = bin_grid_type_id
        if source_bin_grid_id is not None:
          self.source_bin_grid_id = source_bin_grid_id
        if source_bin_grid_app_id is not None:
          self.source_bin_grid_app_id = source_bin_grid_app_id
        if coverage_percent is not None:
          self.coverage_percent = coverage_percent
        if bin_grid_definition_method_type_id is not None:
          self.bin_grid_definition_method_type_id = bin_grid_definition_method_type_id
        if p6_transformation_method is not None:
          self.p6_transformation_method = p6_transformation_method
        if p6_bin_grid_origin_i is not None:
          self.p6_bin_grid_origin_i = p6_bin_grid_origin_i
        if p6_bin_grid_origin_j is not None:
          self.p6_bin_grid_origin_j = p6_bin_grid_origin_j
        if p6_bin_grid_origin_easting is not None:
          self.p6_bin_grid_origin_easting = p6_bin_grid_origin_easting
        if p6_bin_grid_origin_northing is not None:
          self.p6_bin_grid_origin_northing = p6_bin_grid_origin_northing
        if p6_scale_factor_of_bin_grid is not None:
          self.p6_scale_factor_of_bin_grid = p6_scale_factor_of_bin_grid
        if p6_bin_width_on_iaxis is not None:
          self.p6_bin_width_on_iaxis = p6_bin_width_on_iaxis
        if p6_bin_width_on_jaxis is not None:
          self.p6_bin_width_on_jaxis = p6_bin_width_on_jaxis
        if p6_map_grid_bearing_of_bin_grid_jaxis is not None:
          self.p6_map_grid_bearing_of_bin_grid_jaxis = p6_map_grid_bearing_of_bin_grid_jaxis
        if p6_bin_node_increment_on_iaxis is not None:
          self.p6_bin_node_increment_on_iaxis = p6_bin_node_increment_on_iaxis
        if p6_bin_node_increment_on_jaxis is not None:
          self.p6_bin_node_increment_on_jaxis = p6_bin_node_increment_on_jaxis
        if abcd_bin_grid_spatial_location is not None:
          self.abcd_bin_grid_spatial_location = abcd_bin_grid_spatial_location

    @property
    def bin_grid_name(self):
        """
        Gets the bin_grid_name of this AbstractBinGrid.

        :return: The bin_grid_name of this AbstractBinGrid.
        :rtype: str
        """
        return self._bin_grid_name

    @bin_grid_name.setter
    def bin_grid_name(self, bin_grid_name):
        """
        Sets the bin_grid_name of this AbstractBinGrid.

        :param bin_grid_name: The bin_grid_name of this AbstractBinGrid.
        :type: str
        """

        self._bin_grid_name = bin_grid_name

    @property
    def bin_grid_type_id(self):
        """
        Gets the bin_grid_type_id of this AbstractBinGrid.

        :return: The bin_grid_type_id of this AbstractBinGrid.
        :rtype: str
        """
        return self._bin_grid_type_id

    @bin_grid_type_id.setter
    def bin_grid_type_id(self, bin_grid_type_id):
        """
        Sets the bin_grid_type_id of this AbstractBinGrid.

        :param bin_grid_type_id: The bin_grid_type_id of this AbstractBinGrid.
        :type: str
        """

        self._bin_grid_type_id = bin_grid_type_id

    @property
    def source_bin_grid_id(self):
        """
        Gets the source_bin_grid_id of this AbstractBinGrid.

        :return: The source_bin_grid_id of this AbstractBinGrid.
        :rtype: int
        """
        return self._source_bin_grid_id

    @source_bin_grid_id.setter
    def source_bin_grid_id(self, source_bin_grid_id):
        """
        Sets the source_bin_grid_id of this AbstractBinGrid.

        :param source_bin_grid_id: The source_bin_grid_id of this AbstractBinGrid.
        :type: int
        """

        self._source_bin_grid_id = source_bin_grid_id

    @property
    def source_bin_grid_app_id(self):
        """
        Gets the source_bin_grid_app_id of this AbstractBinGrid.

        :return: The source_bin_grid_app_id of this AbstractBinGrid.
        :rtype: str
        """
        return self._source_bin_grid_app_id

    @source_bin_grid_app_id.setter
    def source_bin_grid_app_id(self, source_bin_grid_app_id):
        """
        Sets the source_bin_grid_app_id of this AbstractBinGrid.

        :param source_bin_grid_app_id: The source_bin_grid_app_id of this AbstractBinGrid.
        :type: str
        """

        self._source_bin_grid_app_id = source_bin_grid_app_id

    @property
    def coverage_percent(self):
        """
        Gets the coverage_percent of this AbstractBinGrid.

        :return: The coverage_percent of this AbstractBinGrid.
        :rtype: float
        """
        return self._coverage_percent

    @coverage_percent.setter
    def coverage_percent(self, coverage_percent):
        """
        Sets the coverage_percent of this AbstractBinGrid.

        :param coverage_percent: The coverage_percent of this AbstractBinGrid.
        :type: float
        """

        self._coverage_percent = coverage_percent

    @property
    def bin_grid_definition_method_type_id(self):
        """
        Gets the bin_grid_definition_method_type_id of this AbstractBinGrid.

        :return: The bin_grid_definition_method_type_id of this AbstractBinGrid.
        :rtype: str
        """
        return self._bin_grid_definition_method_type_id

    @bin_grid_definition_method_type_id.setter
    def bin_grid_definition_method_type_id(self, bin_grid_definition_method_type_id):
        """
        Sets the bin_grid_definition_method_type_id of this AbstractBinGrid.

        :param bin_grid_definition_method_type_id: The bin_grid_definition_method_type_id of this AbstractBinGrid.
        :type: str
        """

        self._bin_grid_definition_method_type_id = bin_grid_definition_method_type_id

    @property
    def p6_transformation_method(self):
        """
        Gets the p6_transformation_method of this AbstractBinGrid.

        :return: The p6_transformation_method of this AbstractBinGrid.
        :rtype: int
        """
        return self._p6_transformation_method

    @p6_transformation_method.setter
    def p6_transformation_method(self, p6_transformation_method):
        """
        Sets the p6_transformation_method of this AbstractBinGrid.

        :param p6_transformation_method: The p6_transformation_method of this AbstractBinGrid.
        :type: int
        """

        self._p6_transformation_method = p6_transformation_method

    @property
    def p6_bin_grid_origin_i(self):
        """
        Gets the p6_bin_grid_origin_i of this AbstractBinGrid.

        :return: The p6_bin_grid_origin_i of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_grid_origin_i

    @p6_bin_grid_origin_i.setter
    def p6_bin_grid_origin_i(self, p6_bin_grid_origin_i):
        """
        Sets the p6_bin_grid_origin_i of this AbstractBinGrid.

        :param p6_bin_grid_origin_i: The p6_bin_grid_origin_i of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_grid_origin_i = p6_bin_grid_origin_i

    @property
    def p6_bin_grid_origin_j(self):
        """
        Gets the p6_bin_grid_origin_j of this AbstractBinGrid.

        :return: The p6_bin_grid_origin_j of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_grid_origin_j

    @p6_bin_grid_origin_j.setter
    def p6_bin_grid_origin_j(self, p6_bin_grid_origin_j):
        """
        Sets the p6_bin_grid_origin_j of this AbstractBinGrid.

        :param p6_bin_grid_origin_j: The p6_bin_grid_origin_j of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_grid_origin_j = p6_bin_grid_origin_j

    @property
    def p6_bin_grid_origin_easting(self):
        """
        Gets the p6_bin_grid_origin_easting of this AbstractBinGrid.

        :return: The p6_bin_grid_origin_easting of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_grid_origin_easting

    @p6_bin_grid_origin_easting.setter
    def p6_bin_grid_origin_easting(self, p6_bin_grid_origin_easting):
        """
        Sets the p6_bin_grid_origin_easting of this AbstractBinGrid.

        :param p6_bin_grid_origin_easting: The p6_bin_grid_origin_easting of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_grid_origin_easting = p6_bin_grid_origin_easting

    @property
    def p6_bin_grid_origin_northing(self):
        """
        Gets the p6_bin_grid_origin_northing of this AbstractBinGrid.

        :return: The p6_bin_grid_origin_northing of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_grid_origin_northing

    @p6_bin_grid_origin_northing.setter
    def p6_bin_grid_origin_northing(self, p6_bin_grid_origin_northing):
        """
        Sets the p6_bin_grid_origin_northing of this AbstractBinGrid.

        :param p6_bin_grid_origin_northing: The p6_bin_grid_origin_northing of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_grid_origin_northing = p6_bin_grid_origin_northing

    @property
    def p6_scale_factor_of_bin_grid(self):
        """
        Gets the p6_scale_factor_of_bin_grid of this AbstractBinGrid.

        :return: The p6_scale_factor_of_bin_grid of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_scale_factor_of_bin_grid

    @p6_scale_factor_of_bin_grid.setter
    def p6_scale_factor_of_bin_grid(self, p6_scale_factor_of_bin_grid):
        """
        Sets the p6_scale_factor_of_bin_grid of this AbstractBinGrid.

        :param p6_scale_factor_of_bin_grid: The p6_scale_factor_of_bin_grid of this AbstractBinGrid.
        :type: float
        """

        self._p6_scale_factor_of_bin_grid = p6_scale_factor_of_bin_grid

    @property
    def p6_bin_width_on_iaxis(self):
        """
        Gets the p6_bin_width_on_iaxis of this AbstractBinGrid.

        :return: The p6_bin_width_on_iaxis of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_width_on_iaxis

    @p6_bin_width_on_iaxis.setter
    def p6_bin_width_on_iaxis(self, p6_bin_width_on_iaxis):
        """
        Sets the p6_bin_width_on_iaxis of this AbstractBinGrid.

        :param p6_bin_width_on_iaxis: The p6_bin_width_on_iaxis of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_width_on_iaxis = p6_bin_width_on_iaxis

    @property
    def p6_bin_width_on_jaxis(self):
        """
        Gets the p6_bin_width_on_jaxis of this AbstractBinGrid.

        :return: The p6_bin_width_on_jaxis of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_bin_width_on_jaxis

    @p6_bin_width_on_jaxis.setter
    def p6_bin_width_on_jaxis(self, p6_bin_width_on_jaxis):
        """
        Sets the p6_bin_width_on_jaxis of this AbstractBinGrid.

        :param p6_bin_width_on_jaxis: The p6_bin_width_on_jaxis of this AbstractBinGrid.
        :type: float
        """

        self._p6_bin_width_on_jaxis = p6_bin_width_on_jaxis

    @property
    def p6_map_grid_bearing_of_bin_grid_jaxis(self):
        """
        Gets the p6_map_grid_bearing_of_bin_grid_jaxis of this AbstractBinGrid.

        :return: The p6_map_grid_bearing_of_bin_grid_jaxis of this AbstractBinGrid.
        :rtype: float
        """
        return self._p6_map_grid_bearing_of_bin_grid_jaxis

    @p6_map_grid_bearing_of_bin_grid_jaxis.setter
    def p6_map_grid_bearing_of_bin_grid_jaxis(self, p6_map_grid_bearing_of_bin_grid_jaxis):
        """
        Sets the p6_map_grid_bearing_of_bin_grid_jaxis of this AbstractBinGrid.

        :param p6_map_grid_bearing_of_bin_grid_jaxis: The p6_map_grid_bearing_of_bin_grid_jaxis of this AbstractBinGrid.
        :type: float
        """

        self._p6_map_grid_bearing_of_bin_grid_jaxis = p6_map_grid_bearing_of_bin_grid_jaxis

    @property
    def p6_bin_node_increment_on_iaxis(self):
        """
        Gets the p6_bin_node_increment_on_iaxis of this AbstractBinGrid.

        :return: The p6_bin_node_increment_on_iaxis of this AbstractBinGrid.
        :rtype: int
        """
        return self._p6_bin_node_increment_on_iaxis

    @p6_bin_node_increment_on_iaxis.setter
    def p6_bin_node_increment_on_iaxis(self, p6_bin_node_increment_on_iaxis):
        """
        Sets the p6_bin_node_increment_on_iaxis of this AbstractBinGrid.

        :param p6_bin_node_increment_on_iaxis: The p6_bin_node_increment_on_iaxis of this AbstractBinGrid.
        :type: int
        """

        self._p6_bin_node_increment_on_iaxis = p6_bin_node_increment_on_iaxis

    @property
    def p6_bin_node_increment_on_jaxis(self):
        """
        Gets the p6_bin_node_increment_on_jaxis of this AbstractBinGrid.

        :return: The p6_bin_node_increment_on_jaxis of this AbstractBinGrid.
        :rtype: int
        """
        return self._p6_bin_node_increment_on_jaxis

    @p6_bin_node_increment_on_jaxis.setter
    def p6_bin_node_increment_on_jaxis(self, p6_bin_node_increment_on_jaxis):
        """
        Sets the p6_bin_node_increment_on_jaxis of this AbstractBinGrid.

        :param p6_bin_node_increment_on_jaxis: The p6_bin_node_increment_on_jaxis of this AbstractBinGrid.
        :type: int
        """

        self._p6_bin_node_increment_on_jaxis = p6_bin_node_increment_on_jaxis

    @property
    def abcd_bin_grid_spatial_location(self):
        """
        Gets the abcd_bin_grid_spatial_location of this AbstractBinGrid.

        :return: The abcd_bin_grid_spatial_location of this AbstractBinGrid.
        :rtype: AbstractSpatialLocation
        """
        return self._abcd_bin_grid_spatial_location

    @abcd_bin_grid_spatial_location.setter
    def abcd_bin_grid_spatial_location(self, abcd_bin_grid_spatial_location):
        """
        Sets the abcd_bin_grid_spatial_location of this AbstractBinGrid.

        :param abcd_bin_grid_spatial_location: The abcd_bin_grid_spatial_location of this AbstractBinGrid.
        :type: AbstractSpatialLocation
        """

        self._abcd_bin_grid_spatial_location = abcd_bin_grid_spatial_location

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AbstractBinGrid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
