# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AnyCrsGeoJsonFeatureCollection(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'features': 'list[AnyCrsGeoJsonFeature]',
        'bbox': 'list[float]',
        'persistable_reference_crs': 'str',
        'coordinate_reference_system_id': 'str',
        'vertical_unit_z': 'str',
        'persistable_reference_unit_z': 'str'
    }

    attribute_map = {
        'type': 'type',
        'features': 'features',
        'bbox': 'bbox',
        'persistable_reference_crs': 'persistableReferenceCrs',
        'coordinate_reference_system_id': 'CoordinateReferenceSystemID',
        'vertical_unit_id': 'VerticalUnitID',
        'persistable_reference_unit_z': 'persistableReferenceUnitZ'
    }

    def __init__(self, type=None, features=None, bbox=None, persistable_reference_crs=None, coordinate_reference_system_id=None, vertical_unit_z=None, persistable_reference_unit_z=None):
        """
        AnyCrsGeoJsonFeatureCollection - a model defined in Swagger
        """

        self._type = None
        self._features = None
        self._bbox = None
        self._persistable_reference_crs = None
        self._coordinate_reference_system_id = None
        self._vertical_unit_z = None
        self._persistable_reference_unit_z = None

        self.type = type
        self.features = features
        if bbox is not None:
          self.bbox = bbox
        if persistable_reference_crs is not None:
          self.persistable_reference_crs = persistable_reference_crs
        if coordinate_reference_system_id is not None:
          self.coordinate_reference_system_id = coordinate_reference_system_id
        if vertical_unit_z is not None:
          self.vertical_unit_z = vertical_unit_z
        if persistable_reference_unit_z is not None:
          self.persistable_reference_unit_z = persistable_reference_unit_z

    @property
    def type(self):
        """
        Gets the type of this AnyCrsGeoJsonFeatureCollection.

        :return: The type of this AnyCrsGeoJsonFeatureCollection.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AnyCrsGeoJsonFeatureCollection.

        :param type: The type of this AnyCrsGeoJsonFeatureCollection.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["FeatureCollection", "AnyCrsFeatureCollection"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def features(self):
        """
        Gets the features of this AnyCrsGeoJsonFeatureCollection.

        :return: The features of this AnyCrsGeoJsonFeatureCollection.
        :rtype: list[AnyCrsGeoJsonFeature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """
        Sets the features of this AnyCrsGeoJsonFeatureCollection.

        :param features: The features of this AnyCrsGeoJsonFeatureCollection.
        :type: list[AnyCrsGeoJsonFeature]
        """
        if features is None:
            raise ValueError("Invalid value for `features`, must not be `None`")

        self._features = features

    @property
    def bbox(self):
        """
        Gets the bbox of this AnyCrsGeoJsonFeatureCollection.

        :return: The bbox of this AnyCrsGeoJsonFeatureCollection.
        :rtype: list[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox):
        """
        Sets the bbox of this AnyCrsGeoJsonFeatureCollection.

        :param bbox: The bbox of this AnyCrsGeoJsonFeatureCollection.
        :type: list[float]
        """

        self._bbox = bbox

    @property
    def persistable_reference_crs(self):
        """
        Gets the persistable_reference_crs of this AnyCrsGeoJsonFeatureCollection.
        The spatial context of this AnyCrsGeoJsonFeatureCollection as persistable reference string.

        :return: The persistable_reference_crs of this AnyCrsGeoJsonFeatureCollection.
        :rtype: str
        """
        return self._persistable_reference_crs

    @persistable_reference_crs.setter
    def persistable_reference_crs(self, persistable_reference_crs):
        """
        Sets the persistable_reference_crs of this AnyCrsGeoJsonFeatureCollection.
        The spatial context of this AnyCrsGeoJsonFeatureCollection as persistable reference string.

        :param persistable_reference_crs: The persistable_reference_crs of this AnyCrsGeoJsonFeatureCollection.
        :type: str
        """

        self._persistable_reference_crs = persistable_reference_crs

    @property
    def coordinate_reference_system_id(self):
        """
        Gets the coordinate_reference_system_id of this AnyCrsGeoJsonFeatureCollection.
        The spatial context of this AnyCrsGeoJsonFeatureCollection as a CoordinateReferenceSystemID.

        :return: The coordinate_reference_system_id of this AnyCrsGeoJsonFeatureCollection.
        :rtype: str
        """
        return self._coordinate_reference_system_id

    @coordinate_reference_system_id.setter
    def coordinate_reference_system_id(self, coordinate_reference_system_id):
        """
        Sets the coordinate_reference_system_id of this AnyCrsGeoJsonFeatureCollection.
        The spatial context of this AnyCrsGeoJsonFeatureCollection as a CoordinateReferenceSystemID.

        :param coordinate_reference_system_id: The coordinate_reference_system_id of this AnyCrsGeoJsonFeatureCollection.
        :type: str
        """

        self._coordinate_reference_system_id = coordinate_reference_system_id

    @property
    def vertical_unit_z(self):
        """
        Gets the vertical_unit_z of this AnyCrsGeoJsonFeatureCollection.
        The vertical axis unit for this AnyCrsGeoJsonFeatureCollection as a record ID.

        :return: The vertical_unit_z of this AnyCrsGeoJsonFeatureCollection.
        :rtype: str
        """
        return self._vertical_unit_z

    @vertical_unit_z.setter
    def vertical_unit_z(self, vertical_unit_z):
        """
        Sets the vertical_unit_z of this AnyCrsGeoJsonFeatureCollection.
        The vertical axis unit for this AnyCrsGeoJsonFeatureCollection as a record ID.

        :param vertical_unit_z: The vertical_unit_z of this AnyCrsGeoJsonFeatureCollection.
        :type: str
        """

        self._vertical_unit_z = vertical_unit_z

    @property
    def persistable_reference_unit_z(self):
        """
        Gets the persistable_reference_unit_z of this AnyCrsGeoJsonFeatureCollection.
        The vertical axis unit for this AnyCrsGeoJsonFeatureCollection as persistable reference string.

        :return: The persistable_reference_unit_z of this AnyCrsGeoJsonFeatureCollection.
        :rtype: str
        """
        return self._persistable_reference_unit_z

    @persistable_reference_unit_z.setter
    def persistable_reference_unit_z(self, persistable_reference_unit_z):
        """
        Sets the persistable_reference_unit_z of this AnyCrsGeoJsonFeatureCollection.
        The vertical axis unit for this AnyCrsGeoJsonFeatureCollection as persistable reference string.

        :param persistable_reference_unit_z: The persistable_reference_unit_z of this AnyCrsGeoJsonFeatureCollection.
        :type: str
        """

        self._persistable_reference_unit_z = persistable_reference_unit_z

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AnyCrsGeoJsonFeatureCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
