# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PointProperties(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'inline': 'int',
        'crossline': 'int'
    }

    attribute_map = {
        'label': 'Label',
        'inline': 'Inline',
        'crossline': 'Crossline'
    }

    def __init__(self, label=None, inline=None, crossline=None):
        """
        PointProperties - a model defined in Swagger
        """

        self._label = None
        self._inline = None
        self._crossline = None

        if label is not None:
          self.label = label
        if inline is not None:
          self.inline = inline
        if crossline is not None:
          self.crossline = crossline

    @property
    def label(self):
        """
        Gets the label of this PointProperties.

        :return: The label of this PointProperties.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this PointProperties.

        :param label: The label of this PointProperties.
        :type: str
        """

        self._label = label

    @property
    def inline(self):
        """
        Gets the inline of this PointProperties.

        :return: The inline of this PointProperties.
        :rtype: int
        """
        return self._inline

    @inline.setter
    def inline(self, inline):
        """
        Sets the inline of this PointProperties.

        :param inline: The inline of this PointProperties.
        :type: int
        """

        self._inline = inline

    @property
    def crossline(self):
        """
        Gets the crossline of this PointProperties.

        :return: The crossline of this PointProperties.
        :rtype: int
        """
        return self._crossline

    @crossline.setter
    def crossline(self, crossline):
        """
        Sets the crossline of this PointProperties.

        :param crossline: The crossline of this PointProperties.
        :type: int
        """

        self._crossline = crossline

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PointProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
