server.port=8080
server.servlet.application-display-name=${spring_application_name}
server.error.whitelabel.enabled=true
spring.mvc.throw-exception-if-no-handler-found=true
# Application name
spring.application.name=${spring_application_name}
server.servlet.contextPath=${server.servlet.contextPath}
service.domain.name=${service_domain_name}

osdu.entitlement.url=${ENTITLEMENT_URL}
osdu.entitlement.storage=${STORAGE_URL}
azure.cryptography.enabled=false
azure.datalakestorage.enabled=false
azure.serviceBus.manager.enabled=false
azure.eventgrid.topic.enabled=false
azure.eventgrid.manager.enabled=false
azure.keyvault.url=${KEYVAULT_URI}
azure.activedirectory.app-resource-id=${aad_client_id}
azure.istio.auth.enabled=true
azure.application-insights.instrumentation-key=${appinsights_key}

logging.level.org.springframework.web=INFO
logging.transaction.enabled=true
logging.slf4jlogger.enabled=true
logging.mdccontext.enabled=true
logging.ignore.servlet.paths=/swagger-ui.html
LOG_PREFIX=converter

# Disable keyVault for actuator health check
management.health.azure-key-vault.enabled=false