#!/bin/bash -eu
#
# Copyright 2017-2019, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#!/usr/bin/env bash

# set -e

if [ -z "${INTEGRATION_TESTER-}" ] && [ -z "${1}" ]
then
    echo "Missing argument INTEGRATION_TESTER. It is generated by Google Cloud for the integration tester service account."
    exit 1
fi

export VIRTUAL_SERVICE_HOST_NAME=$HOST_URL
export INTEGRATION_TESTER=${1:-$INTEGRATION_TESTER}
export GOOGLE_AUDIENCES=${2:-$GOOGLE_AUDIENCES}

which python3.6 || { sudo add-apt-repository ppa:deadsnakes/ppa; sudo apt-get update; sudo apt-get install python3.6 python3-pip python3.6-venv; python3.6 --version; }
python3.6 -m venv env
sed -i 's/$1/${1:-}/' env/bin/activate # Fix deactivation bug '$1 unbound variable'
source env/bin/activate
python3.6 -m pip install --upgrade pip
python3.6 -m pip install -r requirements.txt

# Run tests
python3.6 run_test.py

TEST_STATUS=$?

python3.6 -m pip freeze > requirements.txt
python3.6 -m pip uninstall -r requirements.txt -y
deactivate
rm -rf env/

if [ $TEST_STATUS -ne 0 ]
then
    exit 1
fi
