# coding: utf-8

"""
    CRS Conversion Service

    Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ScaleConvergence(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scalefactor': 'float',
        'convergence': 'float',
        'point': 'Point'
    }

    attribute_map = {
        'scalefactor': 'scalefactor',
        'convergence': 'convergence',
        'point': 'point'
    }

    def __init__(self, scalefactor=None, convergence=None, point=None):
        """
        ScaleConvergence - a model defined in Swagger
        """

        self._scalefactor = None
        self._convergence = None
        self._point = None

        if scalefactor is not None:
          self.scalefactor = scalefactor
        if convergence is not None:
          self.convergence = convergence
        if point is not None:
          self.point = point

    @property
    def scalefactor(self):
        """
        Gets the scalefactor of this ScaleConvergence.
        Multiplier to correct a distance along the ellipsoid (“geodetic distance”) to the grid plane of the map projection (“grid distance”). Note: only a conformal map projection has the same point scale factor in all directions at a given location

        :return: The scalefactor of this ScaleConvergence.
        :rtype: float
        """
        return self._scalefactor

    @scalefactor.setter
    def scalefactor(self, scalefactor):
        """
        Sets the scalefactor of this ScaleConvergence.
        Multiplier to correct a distance along the ellipsoid (“geodetic distance”) to the grid plane of the map projection (“grid distance”). Note: only a conformal map projection has the same point scale factor in all directions at a given location

        :param scalefactor: The scalefactor of this ScaleConvergence.
        :type: float
        """

        self._scalefactor = scalefactor

    @property
    def convergence(self):
        """
        Gets the convergence of this ScaleConvergence.
        Grid convergence is important in wellbore positioning if azimuth angles are reported referenced to Grid North and observations need to be corrected. 

        :return: The convergence of this ScaleConvergence.
        :rtype: float
        """
        return self._convergence

    @convergence.setter
    def convergence(self, convergence):
        """
        Sets the convergence of this ScaleConvergence.
        Grid convergence is important in wellbore positioning if azimuth angles are reported referenced to Grid North and observations need to be corrected. 

        :param convergence: The convergence of this ScaleConvergence.
        :type: float
        """

        self._convergence = convergence

    @property
    def point(self):
        """
        Gets the point of this ScaleConvergence.

        :return: The point of this ScaleConvergence.
        :rtype: Point
        """
        return self._point

    @point.setter
    def point(self, point):
        """
        Sets the point of this ScaleConvergence.

        :param point: The point of this ScaleConvergence.
        :type: Point
        """

        self._point = point

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ScaleConvergence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
